title: Karen Funderburk
logo: /assets/img/headshot.jpg
description: Welcome! This website is a collection of my data science projects. A full list can be found (here)[https://pandas.pydata.org/docs/reference/series.html]
show_downloads: false
theme: jekyll-theme-minimal
linked_in: https://www.linkedin.com/in/kmfunder
mail_to: mailto:karenfunderburk94@gmail.com
