title: Karen Funderburk
logo: /assets/img/headshot_circle.jpeg
#description: text
show_downloads: false
theme: jekyll-theme-minimal
linked_in: https://www.linkedin.com/in/kmfunder
mail_to: mailto:karenfunderburk94@gmail.com
